### ISSUE TITLE
challenge:  fixing the N+1 Problem in the users creation script

### ISSUE THREAD

**Issue by stormsidali2001** [stormsidali2001/contracts-management#2]

**Comment by Emilia-mazari** [comment]
can you assign me this issue.

**Comment by stormsidali2001** [comment]
Okay go ahead

**Comment by Emilia-mazari** [comment]
i solved the problem , can you check my pull request.

**Comment by stormsidali2001** [comment]
Thank you for your contribution , the issue has been resolved just how it should be.
